### ISSUE TITLE
Duplicate governance actions

### ISSUE THREAD

**Issue by ElliotFriedman** [solidity-labs-io/forge-proposal-simulator#51]
A single governance proposal should likely only ever do the same action once. If there are duplicate structures, meaning same address and same calldata in a single proposal, FPS should either log a warning, or revert to prevent users from creating governance proposals with duplicate actions.

**Comment by anajuliabit** [comment]
Remediate here https://github.com/solidity-labs-io/forge-proposal-simulator/pull/48/commits/ff4463ff6d2b1ec3ec70a026fbef73f456f54ea6
