### ISSUE TITLE
Simplify type checking docs (perhaps delete feature?) 

### ISSUE THREAD

**Issue by anajuliabit** [solidity-labs-io/forge-proposal-simulator#80]
Currently, the type checking docs, including README.md and the files inside docs/, is too complex and difficult to understand. We should either simplify the documentation or remove the features completely, as Foundry now supports essentially the same feature.

**Comment by ElliotFriedman** [comment]
I agree that we should remove this feature. That way we can remove all node_modules and js/ts deps.
